### ISSUE TITLE
ベンチマークの環境変数について

### ISSUE THREAD

**Issue by yuki2006** [nri-isucon/nri-isucon2022#1]
こんにちは、練習で使わさせて頂いております。ありがとうございます。

ベンチマークの実行方法について

https://github.com/nri-isucon/nri-isucon2022/blob/main/docs/vagrant.md?plain=1#L56

```
TARGET_PORT=80 TARGET_IP_ADDR=127.0.0.1 
```

がおそらく正しいと思うのですがいかがでしょうか？

**Comment by w2-yamaguchi** [comment]
@yuki2006 はじめまして、ご報告ありがとうございます。
また、ご活用いただきありがとうございます。

確かにドキュメントが誤っておりまして、記載いただいた内容が正しいです。
ドキュメントを修正いたします。
